version: '3.1'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: qqqqqq
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080

  web:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

